import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Fotter from '@/components/Fotter'
import Image from 'next/image'
import bg from '@/assets/bg.avif'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    
    <html lang="en">
      
      <body className=" " >
      {/* <Header/> */}

<div>



{children}
<Toaster />
</div>
       
       
        {/* <Fotter/> */}
        </body>
    </html>
  )
}
